export const items = [
  { id: 1, name: "Mens Waterproof Jacket", price: 25, imgPath: require('./assets/images/waterproof-jacket.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/waterproof-jacket.jpg') }, { id: 2, imgPath: require('./assets/images/waterproof-jacket-2.jpg') } ], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 50, rating: 4.5, category: 'male' },
  { id: 2, name: "Black Military Shirt", price: 30, imgPath: require('./assets/images/black-military-shirt.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/black-military-shirt.jpg') }, { id: 2, imgPath: require('./assets/images/black-military-shirt-2.jpg') }, { id: 3, imgPath: require('./assets/images/black-military-shirt-3.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 3, name: "Womens Formal Dress", price: 28, imgPath: require('./assets/images/womens-formal-dress.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/womens-formal-dress.jpg')}, { id: 2, imgPath: require('./assets/images/womens-formal-dress-2.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 32, rating: 4.9, category: 'female' },
  { id: 4, name: "Mens Autumn Jacket", price: 29, imgPath: require('./assets/images/mens-jacket-autumn.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/mens-jacket-autumn.jpg') }, { id: 2, imgPath: require('./assets/images/mens-jacket-autumn-2.jpg')} ], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 23, rating: 5, category: 'male' },
  { id: 5, name: "Womens Summer Dress", price: 35, imgPath: require('./assets/images/summer-dresses-one-shoulderr-ruffles.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/summer-dresses-one-shoulderr-ruffles.jpg') }, { id: 2, imgPath: require('./assets/images/summer-dresses-one-shoulderr-ruffles-2.jpg')}], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 15, rating: 5, category: 'female' },
  { id: 6, name: "Casual Mens Jacket", price: 30, imgPath: require('./assets/images/casual-mens-jacket.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/casual-mens-jacket.jpg')}, { id: 2, imgPath: require('./assets/images/casual-mens-jacket-2.jpg')}], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 50, rating: 4, category: 'male', category: 'male' },
  { id: 7, name: "Size Cotton Bed Sheet", price: 40, imgPath: require('./assets/images/size-cotton-bed-sheet.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/size-cotton-bed-sheet.jpg') }, { id: 2, imgPath: require('./assets/images/size-cotton-bed-sheet-2.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.2, category: 'home' },
  { id: 8, name: "Sleeved Shirt", price: 25, imgPath: require('./assets/images/sleeved_shirt.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/sleeved_shirt.jpg')}, { id: 2, imgPath: require('./assets/images/sleeved-shirt-2.jpg')}], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 48, rating: 5, category: 'male' },
  { id: 9, name: "Casual Two Piece Coat", price: 36, imgPath: require('./assets/images/Sheath-O-Neck-Mini-Dress-Casual-Coat-Two-Pieces.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/Sheath-O-Neck-Mini-Dress-Casual-Coat-Two-Pieces.jpg') }, { id: 2, imgPath: require('./assets/images/Sheath-O-Neck-Mini-Dress-Casual-Coat-Two-Pieces-2.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 15, rating: 4.9, category: 'female' },
  { id: 10, name: "Woman Dress Pocket", price: 25, imgPath: require('./assets/images/Women-Dresses-With-Pocket-Solid-Color-Long-Sleeve.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/Women-Dresses-With-Pocket-Solid-Color-Long-Sleeve.jpg') }, { id: 2, imgPath: require('./assets/images/Women-Dresses-With-Pocket-Solid-Color-Long-Sleeve-2.jpg') } ], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 25, rating: 4.3, category: 'female' },
  { id: 11, name: "Global Village BedSheet", price: 20, imgPath: require('./assets/images/global-village-bed-sheet.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/global-village-bed-sheet.jpg') }, { id: 2, imgPath: require('./assets/images/global-village-bed-sheet-2.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 52, rating: 3.9, category: 'home' },
  { id: 12, name: "Kids Toddler Cloth", price: 10, imgPath: require('./assets/images/kids-toddler-cloth.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/kids-toddler-cloth.jpg') }, { id: 2, imgPath: require('./assets/images/kids-toddler-cloth-2.jpg')}], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 250, rating: 4.8, category: 'kid' },
  { id: 13, name: "Men Formal Business Vest Jacket", price: 24, imgPath: require('./assets/images/Men-Formal-Business-Vest-Jacket.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/Men-Formal-Business-Vest-Jacket.jpg') }, { id: 2, imgPath: require('./assets/images/Men-Formal-Business-Vest-Jacket-2.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 250, rating: 4.8, category: 'male' },
  { id: 16, name: "Ellesse Hoodie", price: 30, imgPath: require('./assets/images/ellesse_hoodie.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/ellesse_hoodie.jpg') }, { id: 2, imgPath: require('./assets/images/ellesse-hoodie-2.jpg')}, { id: 3, imgPath: require('./assets/images/ellesse-hoodie-3.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 450, rating: 5, category: 'male' }
]